

from pipelines.shared.interfaces.pipelines.stage.transform.to_interim.cvm.to_interim_worker_A import ToInterimWorkerInterfaceA


class ToInterimWorkerA(ToInterimWorkerInterfaceA):


    def __init__(
        self,
        *,
        pipeline: str,
    ) -> None:
        
        super().__init__(
            pipeline=pipeline
        )


    def _columns_to_cast(self) -> dict[str, str]:

        return {
            'Acionista': "string",
            'Acionista_Controlador': "string",
            'Acionista_Relacionado': "string",
            'Administradora': "string",
            'Auditor': "string",
            'Bairro': "string",
            'Baseada_Acoes': "string",
            'CATEG_DOC': "string",
            'CD_CVM': "string",
            'CEP': "string",
            'CNPJ': "string",
            'CNPJ_Auditor': "string",
            'CNPJ_CIA': "string",
            'CNPJ_Companhia': "string",
            'CNPJ_Emissor': "string",
            'CNPJ_Emissor_Pessoa_Relacionada': "string",
            'CPF': "string",
            'CPF_Administrador': "string",
            'CPF_Auditor': "string",
            'CPF_CNPJ_Acionista': "string",
            'CPF_CNPJ_Acionista_Relacionado': "string",
            'CPF_CNPJ_Representante_legal': "string",
            'CPF_Pessoa_Relacionada': "string",
            'CPF_Responsavel_Tecnico': "string",
            'Caracteristicas_Divida': "string",
            'Caracteristicas_Reembolso_Capital': "string",
            'Caracteristicas_Valores_Mobiliarios_Divida': "string",
            'Cargo_Administrador': "string",
            'Cargo_Eletivo_Ocupado': "string",
            'Cargo_Ocupado': "string",
            'Cargo_Pessoa_Relacionada': "string",
            'Cargo_Pessoa_Vinculada': "string",
            'Cargo_Responsavel': "string",
            'Categoria_Pessoa_Relacionada': "string",
            'Cessacao_Cargo': "string",
            'Cidade': "string",
            'Classe_Acao': "string",
            'Classe_Acao_Preferencial': "string",
            'Classe_Acoes_Preferenciais': "string",
            'Codigo_CVM': "string",
            'Codigo_CVM_Auditor': "string",
            'Codigo_Conta': "string",
            'Codigo_Posicao': "string",
            'Complemento': "string",
            'Complemento_Cargo_Eletivo_Ocupado': "string",
            'Condicao_Alteracao_Direitos': "string",
            'Condicao_Conversibilidade': "string",
            'Condicao_Conversibilidade_Efeito_Capital_Social': "string",
            'Condicoes_Conversao': "string",
            'Consequencia_Perda_Direito': "string",
            'Conversibilidade': "string",
            'Criterio_Determinacao_Preco_Emissao': "string",
            'DDD_Telefone': "string",
            'DDI_Telefone': "string",
            'DENOM_CIA': "string",
            'Data_Composicao_Capital_Social': "string",
            'Descricao_Atividades': "string",
            'Descricao_Ativo': "string",
            'Descricao_Banco_Depositario': "string",
            'Descricao_Bem_Ativo': "string",
            'Descricao_Conta': "string",
            'Descricao_Instituicao_Custodiante': "string",
            'Descricao_Operacao': "string",
            'Descricao_Outras_Garantias': "string",
            'Descricao_Outro_Cargo_Ocupado': "string",
            'Descricao_Outro_Indice': "string",
            'Descricao_Outro_Valor_Mobiliario': "string",
            'Descricao_Outros_Comites': "string",
            'Descricao_Outros_Remuneracoes_Fixas': "string",
            'Descricao_Outros_Remuneracoes_Variaveis': "string",
            'Descricao_Proporcao_Certificado': "string",
            'Descricao_Restricao_Circulacao': "string",
            'Descricao_Segmento': "string",
            'Descricao_Valor_Mobiliario': "string",
            'Descricao_Voto_Restrito': "string",
            'Direito_Dividendo': "string",
            'Direito_Reembolso_Capital': "string",
            'Direito_Voto': "string",
            'Dividendo_Distribuido': "string",
            'Dividendo_Distribuido_Lucro_Liquido_Ajustado': "string",
            'Dividendo_Distribuido_Total': "string",
            'Documento_Parte_Relacionada': "string",
            'Documento_Pessoa_Relacionada': "string",
            'Duracao': "string",
            'Duracao_Transacao': "string",
            'Eleito_Controlador': "string",
            'Email': "string",
            'Emprestimo_Divida': "string",
            'Entidade_Administradora_Mercado': "string",
            'Escala_Cotacao': "string",
            'Escala_Moeda': "string",
            'Especie_Acao': "string",
            'Especificacao_Posicao_Contratual_Emissor': "string",
            'Evento_Perda_Direito': "string",
            'Evento_Societario': "string",
            'Experiencia_Profissional': "string",
            'Fator_Cotacao': "string",
            'Fax': "string",
            'Forma_Constituicao_Emissor': "string",
            'Forma_Integralizacao': "string",
            'Forma_Restituicao': "string",
            'Garantia_Seguro': "string",
            'Hipotese_Calculo_Resgate': "string",
            'Hipotese_Resgate_Formula_Calculo': "string",
            'ID_Acionista': "string",
            'ID_Acionista_Relacionado': "string",
            'ID_Auditor': "string",
            'ID_Capital_Social': "string",
            'ID_Capital_Social_Aumento': "string",
            'ID_Capital_Social_Desdobramento': "string",
            'ID_Capital_Social_Reducao': "string",
            'ID_DOC': "string",
            'ID_Documento': "string",
            'ID_Plano_Recompra': "string",
            'ID_Politica': "string",
            'ID_Sociedade': "string",
            'Identificacao_Valor_Mobiliario': "string",
            'Informacao_Financeira': "string",
            'Justificativa_Substituicao': "string",
            'LINK_DOC': "string",
            'Local': "string",
            'Logradouro': "string",
            'Lucro_Liquido_Ajustado': "string",
            'Lucro_Liquido_Retido': "string",
            'Mercado': "string",
            'Mercado_Valor_Mobiliario': "string",
            'Montante_Interesse_Parte_Relacionada': "string",
            'Municipio': "string",
            'Municipio_Sede': "string",
            'Nacionalidade': "string",
            'Nao_Aplicavel': "string",
            'Natureza_Razao_Operacao': "string",
            'Nome': "string",
            'Nome_Administrador': "string",
            'Nome_Companhia': "string",
            'Nome_Emissor': "string",
            'Nome_Emissor_Pessoa_Relacionada': "string",
            'Nome_Pessoa_Relacionada': "string",
            'Nome_Responsavel': "string",
            'Objeto_Contrato': "string",
            'Observacao': "string",
            'Orgao_Administracao': "string",
            'Orgao_Aprovacao': "string",
            'Orgao_Deliberacao_Aumento': "string",
            'Outras_Caracteristicas': "string",
            'Outras_Caracteristicas_Importantes': "string",
            'Outras_Caracteristicas_Relevantes': "string",
            'Outro_Cargo_Funcao': "string",
            'Outros_Valores_Fixos': "string",
            'Outros_Valores_Variaveis': "string",
            'Pais': "string",
            'Pais_Constituicao_Emissor': "string",
            'Pais_Negociacao': "string",
            'Pais_Sede': "string",
            'Parte_Relacionada': "string",
            'Participacoes_Comites': "string",
            'Participante_Acordo_Acionistas': "string",
            'Passivo': "string",
            'Pos_emprego': "string",
            'Posicao': "string",
            'Posicao_Contratual_Emissor': "string",
            'Possibilidade_Resgate': "string",
            'Possui_Registro_CVM': "string",
            'Prazo_Duracao_Emissor': "string",
            'Prazo_Integralizacao': "string",
            'Prazo_Mandato': "string",
            'Principais_Caracteristicas': "string",
            'Profissao': "string",
            'Razao_Apresentada': "string",
            'Razao_Aquisicao_Manutencao': "string",
            'Razao_Reducao': "string",
            'Razao_Social': "string",
            'Reducao_Capital_Anterior': "string",
            'Relacao_Emissor': "string",
            'Remuneracao_Auditor': "string",
            'Representante_Legal': "string",
            'Requisicao_Registro_Emissor': "string",
            'Rescisao': "string",
            'Resgatavel': "string",
            'Residente_Exterior': "string",
            'Responsavel_Tecnico': "string",
            'Restricao_Circulacao': "string",
            'Saldo_Existente': "string",
            'Servico_Contratado': "string",
            'Sigla_Classe_Acoes_Preferenciais': "string",
            'Sigla_Pais_Constituicao_Emissor': "string",
            'Sigla_UF': "string",
            'Subscricao_Capital_Anterior': "string",
            'Telefone': "string",
            'Tipo_Ativo': "string",
            'Tipo_Capital': "string",
            'Tipo_Classe_Acao_Preferencial': "string",
            'Tipo_Comite': "string",
            'Tipo_Evento': "string",
            'Tipo_Garantia': "string",
            'Tipo_Indice': "string",
            'Tipo_Moeda': "string",
            'Tipo_Obrigacao': "string",
            'Tipo_Origem_Auditor': "string",
            'Tipo_Parentesco': "string",
            'Tipo_Pessoa': "string",
            'Tipo_Pessoa_Acionista': "string",
            'Tipo_Pessoa_Acionista_Relacionado': "string",
            'Tipo_Pessoa_Relacionada': "string",
            'Tipo_Pessoa_Representante_Legal': "string",
            'Tipo_Propriedade': "string",
            'Tipo_Relacao': "string",
            'Tipo_Sociedade': "string",
            'Tipo_Subscricao': "string",
            'Titulo_Conversivel_Acao': "string",
            'UF': "string",
            'UF_Sede': "string",
            'VERSAO': "string",
            'Valor': "string",
            'Valor_Mobiliario': "string",
            'Vedacao_Procedimentos_Fiscalizacao': "string",
            'Versao': "string",
        }


    def _columns_to_parse_dates(self) -> list[str]:
        
        return [
            "DT_RECEB", "DT_REFER", "Data_Aprovacao", "Data_Aprovacao_Retencao",
            "Data_Aquisicao", "Data_Autorizacao_Aprovacao", "Data_Constituicao_Emissor",
            "Data_Deliberacao", "Data_Eleicao", "Data_Emissao", "Data_Encerramento",
            "Data_Fim_Contratacao", "Data_Fim_Exercicio_Social", "Data_Fim_Recompra",
            "Data_Fim_Responsavel_Tecnico", "Data_Fim_Trimestre", "Data_Inicio_Contratacao",
            "Data_Inicio_Exercicio_Social", "Data_Inicio_Listagem", "Data_Inicio_Prestacao_Servico",
            "Data_Inicio_Primeiro_Mandato", "Data_Inicio_Recompra", "Data_Inicio_Responsavel_Tecnico",
            "Data_Nascimento", "Data_Operacao", "Data_Pagamento_Dividendo", "Data_Posse",
            "Data_Reducao", "Data_Referencia", "Data_Registro_Emissor", "Data_Transacao",
            "Data_Ultima_Alteracao", "Data_Ultima_Assembleia", "Data_Valor_Contabil",
            "Data_Valor_Mercado", "Data_Vencimento",
        ]


    def _columns_to_cast_to_numeric(self) -> list[str]:
        
        return [
            "Beneficios_Diretos_Indiretos", "Bonus", "Bonus_Valor_Efetivo",
            "Bonus_Valor_Maximo", "Bonus_Valor_Metas_Atingidas", "Bonus_Valor_Minimo",
            "Comissoes", "Diluicao_Potencial", "Divida_1a3Anos", "Divida_3a5Anos",
            "Divida_Inferior_1_Ano", "Divida_Superior_5Anos", "Divida_Total",
            "Indice_Endividamento", "Montante", "Montante_Envolvido",
            "Numero_Mandatos_Consecutivos", "Numero_Membros", "Numero_Membros_Remunerados",
            "Participacao_Emissor", "Participacao_Resultados", "Participacao_Reunioes",
            "Participacao_Valor_Efetivo", "Participacao_Valor_Maximo",
            "Participacao_Valor_Metas_Atingidas", "Participacao_Valor_Minimo", "Percentual",
            "Percentual_Acao_Ordinaria_Circulacao", "Percentual_Acao_Preferencial_Circulacao",
            "Percentual_Acoes", "Percentual_Acoes_Ordinarias_Circulacao",
            "Percentual_Acoes_Preferenciais_Circulacao", "Percentual_Adquirido",
            "Percentual_Circulacao", "Percentual_Participacao_Reunioes", "Percentual_Previsto",
            "Percentual_Relacao_Valores_Mobiliarios_Circulacao", "Percentual_Tag_Along",
            "Percentual_Total_Acoes_Circulacao", "Preco_Emissao", "Preco_Medio_Ponderado_Aquisicao",
            "Preco_Medio_Ponderado_Mercado", "Preco_Medio_Ponderado_Opcoes_Em_Aberto",
            "Preco_Medio_Ponderado_Opcoes_Exercidas", "Preco_Medio_Ponderado_Opcoes_Perdidas",
            "Quantidade", "Quantidade_30a50Anos", "Quantidade_Acao_Ordinaria_Circulacao",
            "Quantidade_Acao_Preferencial_Circulacao", "Quantidade_Acima50Anos",
            "Quantidade_Acionistas_Investidores_Institucionais", "Quantidade_Acionistas_PF",
            "Quantidade_Acionistas_PJ", "Quantidade_Acoes", "Quantidade_Acoes_Antes_Aprovacao",
            "Quantidade_Acoes_Depois_Aprovacao", "Quantidade_Acoes_Ordinarias",
            "Quantidade_Acoes_Ordinarias_Antes_Aprovacao", "Quantidade_Acoes_Ordinarias_Circulacao",
            "Quantidade_Acoes_Ordinarias_Depois_Aprovacao", "Quantidade_Acoes_Preferenciais",
            "Quantidade_Acoes_Preferenciais_Antes_Aprovacao", "Quantidade_Acoes_Preferenciais_Circulacao",
            "Quantidade_Acoes_Preferenciais_Depois_Aprovacao", "Quantidade_Adquirida",
            "Quantidade_Alienada", "Quantidade_Amarelo", "Quantidade_Ate30Anos",
            "Quantidade_Branco", "Quantidade_Cancelada", "Quantidade_Centro_Oeste",
            "Quantidade_Exterior", "Quantidade_Feminino", "Quantidade_Final", "Quantidade_Indigena",
            "Quantidade_Inicial", "Quantidade_Investidor", "Quantidade_Investidor_Institucional",
            "Quantidade_Masculino", "Quantidade_Membros_Remunerados", "Quantidade_Nao_Binario",
            "Quantidade_Nao_PCD", "Quantidade_Nordeste", "Quantidade_Norte", "Quantidade_Outros",
            "Quantidade_PCD", "Quantidade_Pardo", "Quantidade_Pessoa_Fisica",
            "Quantidade_Pessoa_Juridica", "Quantidade_Preto", "Quantidade_Prevista",
            "Quantidade_Sem_Resposta", "Quantidade_Sudeste", "Quantidade_Sul",
            "Quantidade_Total_Acoes", "Quantidade_Total_Acoes_Antes_Aprovacao",
            "Quantidade_Total_Acoes_Circulacao", "Quantidade_Total_Acoes_Depois_Aprovacao",
            "Quantidade_Total_Membros", "Quantidade_Valor_Mobiliario", "Salario", "Saldo_Devedor",
            "Taxa_Juros", "Taxa_Retorno_Patrimonio_Liquido_Emissor", "Total_Remuneracao",
            "Total_Remuneracao_Orgao", "Valor_Capital", "Valor_Contabil", "Valor_Cotacao_Media",
            "Valor_Diferenca_Aquisicao_Mercado", "Valor_Maior_Cotacao", "Valor_Maior_Remuneracao",
            "Valor_Medio_Remuneracao", "Valor_Menor_Cotacao", "Valor_Menor_Remuneracao",
            "Valor_Mercado", "Valor_Montante_Dividendos_Recebidos", "Valor_Nominal",
            "Valor_Preco_Medio", "Valor_Preco_Medio_Adquirido", "Valor_Preco_Medio_Alienado",
            "Valor_Preco_Medio_Cancelado", "Valor_Preco_Medio_Final", "Valor_Preco_Medio_Inicial",
            "Valor_Reserva_Disponivel_Recompra", "Valor_Restituido_Por_Acao", "Valor_Total_Adquirido",
            "Valor_Total_Alienado", "Valor_Total_Cancelado", "Valor_Total_Emissao", "Valor_Total_Final",
            "Valor_Total_Inicial", "Valor_Total_Reducao", "Valor_Volume_Negociado",
            "Variacao_Percentual_Valor_Contabil", "Variacao_Percentual_Valor_Mercado",
        ]
        

