

B3_INDICES = [
    "IDIV", "MLCX", "SMLL", "IVBX", "AGFS", "IFNC", "IBEP", "IBEE", "IBHB", "IFIX",
    "IBLV", "IMOB", "UTIL", "ICON", "IEEX", "IFIL", "IMAT", "INDX", "IBSD", "BDRX",
]


CHECKPOINT_STAGE_EXTRACT = "extract"
CHECKPOINT_STEP_DOWNLOAD = "download"


CHECKPOINT_STAGE_PROCESSED = "processed"
CHECKPOINT_STEP_PROCESSED_1 = "transform_1"


DOWNLOAD_MAX_ATTEMPTS = 3